---
- name: Extract NTP servers from NetBox inventory config_context
  set_fact:
    ntp_servers: "{{ hostvars[inventory_hostname].config_context[0].ntp_servers | default([]) }}"

- name: Render NTP configuration using Jinja2 template
  template:
    src: ntp_config.j2
    dest: /tmp/ntp_config_{{ inventory_hostname }}.yml

- name: Apply NTP configuration to Cisco IOS devices
  when: ansible_network_os == 'ios'
  cisco.ios.ios_ntp_global:
    config: "{{ lookup('file', '/tmp/ntp_config_{{ inventory_hostname }}.yml') | from_yaml }}"
    state: replaced

- name: Apply NTP configuration to Arista EOS devices
  when: ansible_network_os == 'eos'
  arista.eos.eos_ntp_global:
    config: "{{ lookup('file', '/tmp/ntp_config_{{ inventory_hostname }}.yml') | from_yaml }}"
    state: replaced

- name: Remove temporary NTP configuration files
  file:
    path: "/tmp/ntp_config_{{ inventory_hostname }}.yml"
    state: absent