---
- name: Configure Network Services - NTP, Syslog, Name Servers and Domain Name on network devices using NetBox data
  connection: network_cli
  hosts: sites_lab
  gather_facts: no

  roles:
    - role: ntp
    - role: syslog
    - role: name-servers
    - role: domain-name