---
- name: Listen for netbox events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

## Deploy Network Services Configuration on New Device Added
  - name: New Device Added
    condition: event.payload.event == "job_ended" and event.payload.model == "branch" and event.payload.data.log is search("Creating device", ignorecase=true)
    action:
      run_playbook:
        name: configure-network-services.yml
